In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC

In [2]:
df = pd.read_excel('Gadarwara_Q.xlsx')
df

Dates    Year  Month   Day  RF_1  RF_2  RF_3  RF_4  RF_5  RF_6  \
0     1977-06-01  1977.0    6.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
1     1977-06-02  1977.0    6.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0   
2     1977-06-03  1977.0    6.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   
3     1977-06-04  1977.0    6.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0   
4     1977-06-05  1977.0    6.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   
...          ...     ...    ...   ...   ...   ...   ...   ...   ...   ...   
15702 2020-05-28  2020.0    5.0  28.0   0.0   0.0   0.0   0.0   0.0   0.0   
15703 2020-05-29  2020.0    5.0  29.0   0.0   0.0   0.0   0.0   0.0   0.0   
15704 2020-05-30  2020.0    5.0  30.0   1.1   0.3   0.0   0.3   0.0   0.0   
15705 2020-05-31  2020.0    5.0  31.0   0.0   0.0   0.0   0.0   0.0   0.0   
15706        NaT     NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

       RF_7  RF_8  RF_10  LRF     Q  Q(t-1)  
0       0.0   0.0    0.0  0.0  1.60    0.00  
1       0.0   0.0    0.0  0.0  1.60    1.60  
2       0.0   0.0    0.0  0.0  1.60    1.60  
3       0.0   0.0    0.0  0.0  1.60    1.60  
4       0.0   0.0    0.0  0.0  1.60    1.60  
...     ...   ...    ...  ...   ...     ...  
15702   0.0   0.0    0.0  0.0  0.07    0.08  
15703   0.0   0.0    0.0  0.0  0.05    0.07  
15704   0.0   0.0    0.0  0.0  0.05    0.05  
15705   0.0   0.0    0.0  0.0  0.05    0.05  
15706   NaN   NaN    NaN  NaN   NaN    0.05  

[15707 rows x 16 columns]

In [3]:
df['Q(t-1)'] = df['Q(t-1)'].fillna(df['Q(t-1)'].mean())
df['Q'] = df['Q'].fillna(df['Q'].mean())

X = df[['Q(t-1)']]
Y = df['Q']
X

Q(t-1)
0        0.00
1        1.60
2        1.60
3        1.60
4        1.60
...       ...
15702    0.08
15703    0.07
15704    0.05
15705    0.05
15706    0.05

[15707 rows x 1 columns]

In [18]:
score7 = cross_val_score(model, df[["Q(t-1)"]], df.Q, cv = 7)
score7

array([ 0.20262937,  0.26764576,  0.30449072,  0.36842165,  0.0687514 ,
        0.37315908, -0.14523781])

In [13]:
score6 = cross_val_score(model, df[["Q(t-1)"]], df.Q, cv = 6)
score6

array([ 0.22483653,  0.25556911,  0.30210254,  0.32436099,  0.1623166 ,
       -0.05831532])

In [19]:
score5 = cross_val_score(model, df[["Q(t-1)"]], df.Q, cv = 5)
score5

array([ 0.22416021,  0.29662117,  0.33377395,  0.12252612, -0.01045832])